// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18d1-OXMqGMr80YTJ4VBuER_CxLga-zg',
    appId: '1:476708106662:web:40db61972509e618e69f67',
    messagingSenderId: '476708106662',
    projectId: 'leave-management-app-f07b8',
    authDomain: 'leave-management-app-f07b8.firebaseapp.com',
    storageBucket: 'leave-management-app-f07b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBguzU19KqLZLyLCc8R6zFFivFu8jzLX1c',
    appId: '1:476708106662:android:cf9792f064f436b9e69f67',
    messagingSenderId: '476708106662',
    projectId: 'leave-management-app-f07b8',
    storageBucket: 'leave-management-app-f07b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApeDCfdgBQcM_bEzaCcenpLT8uUvxXlPQ',
    appId: '1:476708106662:ios:e09ced937188a55be69f67',
    messagingSenderId: '476708106662',
    projectId: 'leave-management-app-f07b8',
    storageBucket: 'leave-management-app-f07b8.firebasestorage.app',
    iosBundleId: 'com.example.leaveManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApeDCfdgBQcM_bEzaCcenpLT8uUvxXlPQ',
    appId: '1:476708106662:ios:e09ced937188a55be69f67',
    messagingSenderId: '476708106662',
    projectId: 'leave-management-app-f07b8',
    storageBucket: 'leave-management-app-f07b8.firebasestorage.app',
    iosBundleId: 'com.example.leaveManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB18d1-OXMqGMr80YTJ4VBuER_CxLga-zg',
    appId: '1:476708106662:web:2f4f6cc251fa2db9e69f67',
    messagingSenderId: '476708106662',
    projectId: 'leave-management-app-f07b8',
    authDomain: 'leave-management-app-f07b8.firebaseapp.com',
    storageBucket: 'leave-management-app-f07b8.firebasestorage.app',
  );
}
